### ISSUE TITLE
error with grenedalf

### ISSUE THREAD

**Issue by ospfsg** [lczech/grenedalf#22]
Hi Lczech

I run grenedalf and I got this error: 
Started 2024-06-14 14:57:37

Processing 4 samples

At chromosome chromosome_1
At chromosome chromosome_2
At chromosome chromosome_3
At chromosome chromosome_4
At chromosome chromosome_5
At chromosome chromosome_6
At chromosome chromosome_7
At chromosome chromosome_8
At chromosome chromosome_9
Error: Cannot iterate multiple input sources in parallel, as (at least) one of them is not in the correct sorting order. By default, we expect lexicographical sorting of chromosomes, and then sorting by position within chromosomes. Alternatively, when a sequence dictionary is specified (such as from a .dict or .fai file, or from a reference genome .fasta file), we expect the order of chromosomes as specified there. Offending input source: PS2, going from chromosome_9:58459040 to chromosome_10:6

terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot iterate multiple input sources in parallel, as (at least) one of them is not in the correct sorting order. By default, we expect lexicographical sorting of chromosomes, and then sorting by position within chromosomes. Alternatively, when a sequence dictionary is specified (such as from a .dict or .fai file, or from a reference genome .fasta file), we expect the order of chromosomes as specified there. Offending input source: PS2, going from chromosome_9:58459040 to chromosome_10:6
Aborted (core dumped)

the for bam files come from grenepipe/dedup

is this related with the size  of the label?    the problems is when we change form chromossome 9 to 10.

This was my first try with grenedalf and I didn't use a  referrence genome file.

/home/dau1/software/grenedalf-0.5.1/bin/grenedalf diversity --sam-path  PN1.bam  PN2.bam PS1.bam PS2.bam  --pool-sizes pool-sizes.csv  --window-type genome --window-average-policy valid-loci --filter-sample-min-count 2   --filter-sample-min-read-depth 4 --no-extra-columns

thank you

 osp

**Comment by lczech** [comment]
Hey @ospfsg,

the error message tells you what is needed: simply provide a reference genome file (dict, fai, or fasta) that lists the chromosomes in the order in which they are in your samples :-) - see [here](https://github.com/lczech/grenedalf/wiki/Subcommand:-diversity#input-settings)

Otherwise, when reading multiple files, grenedalf has no way of knowing which chromosomes are in which order - for instance, it could happen that one file has order ChrA ChrB ChrC, and another file has the same order, but is missing ChrB. Then, once we are done with ChrA, we have one file starting ChrB, and the other starting ChrC - and need to decide which one to process next. By default, we are just assuming lexicographical order, which works for most such cases. But in that order, going from Chr9 to Chr10 is not in lexicographical order, see [here](https://stackoverflow.com/questions/45950646/what-is-lexicographical-order). By providing a reference genome order, we can get around this, and just use that fixed order instead.

Cheers
Lucas

**Comment by ospfsg** [comment]
Hi Lucas

I provide the fai file generate by grenepipe and it seems working. 

thank you again
osp

**Comment by lczech** [comment]
Happy to hear ;-)
