### ISSUE TITLE
--sam-min-map-qual and depth

### ISSUE THREAD

**Issue by pashapu43** [lczech/grenedalf#27]
Hi,

Thank you for the amazing tool. I have a question on how the --sam-min-map-qual filter works.  According to wiki

_--sam-min-map-qual
UINT:UINT in [0 - 90]=0 Needs: --sam-path
Minimum phred-scaled mapping quality score [0-90] for a read in sam/bam/cram files to be considered. Any read that is below the given value of mapping quality will be completely discarded, and its bases not taken into account. Default is 0, meaning no filtering by base quality._

I have aligned the reads to the genome using BWA MEM and processed the bam files with the following command.

/grenedalf/bin/grenedalf frequency --sam-path Eng_ORG.bam Eng_MID.bam Eng_CUR.bam \
--reference-genome-fasta-file genome.fa \
--sam-min-base-qual 25 --sam-min-map-qual 30 --write-sample-read-depth --write-sample-counts --write-total-read-depth --write-sample-ref-freq --write-total-counts --out-dir ./  --file-prefix p2

My understanding is that only the reads with mapq > 30 will be used to estimate the frequencies, so the read depth of a sample in the output should match the number of reads with mapq score above 30 in the bam file. I am, i correct in assuming this? 

I summed up the DEPTH column if a sample in R  and this value does not match with the number of reads with mapq >30 in the bam file.

```
> sum(fsnp$Eng_MID.DEPTH)
[1] 488310302
```
```
samtools view Eng_MID.bam | awk '$5 > 30' | wc -l
27079399
```
The library size of Eng_MID.fq.gz was ~43 million PE reads

The same is the case with other samples. Is this because of multimapping? if yes how can this affect the allele frequency, diversity estimates and fst? 

Thanks in advance

**Comment by lczech** [comment]
Hi @pashapu43,

thanks for your patience, got a bit swamped. 

> My understanding is that only the reads with mapq > 30 will be used to estimate the frequencies, so the read depth of a sample in the output should match the number of reads with mapq score above 30 in the bam file. I am, i correct in assuming this?

To be exact, the reads _below_ 30 are filtered out, so the ones with mapq >= 30 are kept. But other than that, yes, that's the idea. Per position in the genome, the read depth should match the number of bases that remain after that filter. You are however also setting `--sam-min-base-qual 25`, which in addition removes all bases below base qual 25, so that definitely also has an influence on the result you are seeing.

As for the commands that you are comparing this to: As far as I understand what you did there, the `samtools view` gives you the number of reads with mapq > 30 (as explained above, that should be >= 30 to be exact instead). The `DEPTH` column of the frequency command however gives you the number of bases that were used _per position_ to get the reference/alt count/frequency. That is of course bigger than the number of reads overall, as a single read will cover many positions (across its length).

So, to get the numbers reported via some external tool (e.g., samtools) to match with those of grenedalf, you'd need to do the following: for each read with mapq >= 30, take the number of base with min base quality >= 25 that are mapped to the reference (we ignore indels). That should give you the correct number.

Hope that helps, cheers, and so long
Lucas

**Comment by pashapu43** [comment]
Thank you for taking the time to explain it.

My understanding was depth = read depth. It is clear now. Does grenedalf report read depth (coverage)? if not, how can I calculate the SNPs' read depth?  I would like to filter out snps < a given threshold.

Thanks

**Comment by lczech** [comment]
Hey @pashapu43,

what exactly do you mean by the term "read depth" then? The way you describe it, that sounds exactly like what grenedalf is doing, but I don't think this is what you mean.

Also, see [here](https://github.com/lczech/grenedalf/wiki/Overview#terminology) for some clarification on read depth vs coverage. I am not sure if that is what you have in mind, so please specify what number exactly you mean by "read depth" of a SNP.

Cheers
Lucas

**Comment by pashapu43** [comment]
I am a bit confused now. I am trying to understand what is reported in the DEPTH column in the grenedalf frequency command.

![image](https://github.com/user-attachments/assets/49cbba4f-879f-4890-bea9-4cd432d01b92)


For example, the allele frequency at the locus highlighted with yellow is 0.875 for the reference allele A and 0.125 for the alternate allele T. As 8 reads support this locus, the read depth is 8, no? Is this how the DEPTH is calculated in grenedalf? 

Thanks in advance

**Comment by lczech** [comment]
Yes, exactly that is how we use "read depth" in grenedalf. Good idea to bring in a figure to clarify :-)

So, in the figure, all reads are being used, and hence the depth is 8. However, coming back to your initial question, imagine the last read there had a low mapq. It then would not be considered at the yellow locus, and hence that locus would have 6 A and 1 T, with a read depth of 7 in total. Similarly, if a single base had a low quality, it would also be ignored.

Does that answer your question then? This is how the frequency command is supposed to work. If it doesn't, could you please provide a minimal example, so that I can investigate?

**Comment by pashapu43** [comment]
Thank you for the quick response.

Yes, it answers my question. Given that the depth column is based on the number of reads supporting the SNP positions, the sum of depth across all snps can't be more than the library sizes, right?

In my case, there were approx. 47 million reads in the fastq file that was aligned to the genome with bwa mem. After running grenedalf frequency, I loaded the frequency.csv file into R to check the depth. The sum of the depth column is almost 10 times the library size (47 million). This is my issue, how can the sum of the depth column be more than the number of reads in the fastq file.  

Thanks
Akhil

**Comment by pashapu43** [comment]
Now I understand. I didn't consider that one read can support multiple snps. Apologies for my ignorance. Thanks a lot for taking time and explaining it.

Akhil

**Comment by lczech** [comment]
All good, glad we could clarify that :-)

Also, to be extra precise here: Not all those positions might be SNPs. That is, they might be invariant, with only one base of `ACGT` having any support at the position. In the frequency command. The frequency command reports the data-as is, unless you give it extra options to filter out invariant sites.
