### ISSUE TITLE
Possible Issue with FST Subcommand in Versions Above v0.5

### ISSUE THREAD

**Issue by VitoriaHorvathMiranda** [lczech/grenedalf#32]
Hi Lucas,

Thank you so much for creating this amazing tool! I’m reaching out because I’ve noticed some odd results when using the FST subcommand in versions above v0.5. Specifically, I’m seeing extremely negative FST values, even with some unexpected negative peaks.

For context, I started using grenedalf in its v0.3 release and performed window FST analyses without issues, although I did encounter some challenges with diversity metrics—possibly related to window averaging. Recently, I updated to version 0.6 and noticed the introduction of the --window-average-policy parameter, which likely addresses my previous diversity metric issues.

However, with this update, I began encountering these unusual negative FST values. While I understand that FST can theoretically be negative, and there are some cases where this occurs naturally, the values I’m observing seem off. To investigate further, I re-ran a small genomic region where the FST values were negative in v0.5 or v0.6 using versions v0.3 and v0.4. The results were quite different: I noticed on version 0.4 FST values became much smaller, and the negative values started appearing in v0.5.

I also noticed that on v0.5 you mentioned you fixed some problems regarding FST, which led me to wonder if the fix introduced in that version might have inadvertently caused other issues.

Here are the commands I used for each version:

```
bin/grenedalfv3.0/grenedalf-0.3.0/bin/grenedalf fst     --sync-path negative_FST_window_CT.sync     --reference-genome-fasta-file reference/dmel-all-chromosome-r6.25.fasta     --rename-samples-file negative_sample_names.tsv     --window-type queue     --window-queue-count 100     --window-queue-stride 10     --method unbiased-hudson     --pool-sizes pool_sizes.csv     --verbose     --out-dir .     --file-prefix CT_100_v3_VS_hudson_

bin/grenedalfv4.0/grenedalf-0.4.0/bin/grenedalf fst     --sync-path negative_FST_window_CT.sync     --reference-genome-fasta-file reference/dmel-all-chromosome-r6.25.fasta     --rename-samples-file negative_sample_names.tsv     --window-type queue     --window-queue-count 100     --window-queue-stride 10     --window-average-policy valid-snps     --method unbiased-hudson     --pool-sizes pool_sizes.csv     --verbose     --out-dir .     --file-prefix CT_100_v4_VS_hudson_

bin/grenedalfv5.0/grenedalf-0.5.0/bin/grenedalf fst     --sync-path negative_FST_window_CT.sync     --reference-genome-fasta-file reference/dmel-all-chromosome-r6.25.fasta     --rename-samples-file negative_sample_names.tsv     --window-type queue     --window-queue-count 100     --window-queue-stride 10     --window-average-policy valid-snps     --method unbiased-hudson     --pool-sizes pool_sizes.csv     --verbose     --out-dir .     --file-prefix CT_100_v5_VS_hudson_

bin/grenedalfv6.0/grenedalf-0.6.0/bin/grenedalf fst     --sync-path negative_FST_window_CT.sync     --reference-genome-fasta reference/dmel-all-chromosome-r6.25.fasta     --rename-samples-list negative_sample_names.tsv     --window-type queue     --window-queue-count 100     --window-queue-stride 10     --window-average-policy valid-snps     --method unbiased-hudson     --pool-sizes pool_sizes.csv     --verbose     --out-dir .     --file-prefix CT_100_v6_VS_hudson_
```

I’m also sharing a small sync file I used for the tests, along with the results for each run. For comparison, I calculated FST in R using a custom script (without accounting for the pooled error), and the results were more in line with what I saw in v0.3.

Another thing that caught my attention is that, at least in version 0.6, no matter which ‘--window-average-policy’ I choose the result is exactly the same. In my mind, this is the expected behavior because the window size would end up being canceled anyway. However, the command manual seems to suggest this isn’t the intended behavior

Could you please take a look at this to confirm everything is working as expected? If so, could you help clarify the changes made to FST calculations between v0.3, v0.4, and v0.5?

Thanks again for your help!

Best regards,
Vitória
[grenedalf_issue.zip](https://github.com/user-attachments/files/17002857/grenedalf_issue.zip)

**Comment by lczech** [comment]
Hi Vitória @VitoriaHorvathMiranda,

thank you for the thorough report! Well explained and easy to follow indeed.

> ...which led me to wonder if the fix introduced in that version might have inadvertently caused other issues.

Well, not out of the question that I introduced some more bugs now, but it does not seem to be the case here. Seems that the calculations are done correctly.

> I’m also sharing a small sync file I used for the tests, along with the results for each run. For comparison, I calculated FST in R using a custom script (without accounting for the pooled error), and the results were more in line with what I saw in v0.3.

Hm okay, that very much depends on how you exactly computed that. Thanks to the sync file you shared, I was able to exactly recalculate the values that you observed with each version, just based on the sync file, and simply computing the equations in a spreadsheet, see [negative_FST_window_CT.sync.zip](https://github.com/user-attachments/files/17015512/negative_FST_window_CT.sync.zip). That's an OpenOffice spreadsheet, but I've also printed it as a PDF for ease of access. I think that MS Excel might be able to open this as well, if you want to see the equations. Not sure though. 

But basically, I just computed the very basic equations for Pi between and Pi Within for the first window of the first two populations. And those gave _exactly_ the same results that your result files also show. The only difference is that in grenedalf v0.3.0, the case where one of the populations had zero coverage was still counted towards the total. I've marked these cases in orange in the spreadsheet. This is the only difference in the sums of Pi within values in the two rightmost columns. And that difference in the sums is then the reason for the different results.

In short: This is not even due to the new window averaging options, but simply the result of a more refined treatment of missing data. I think that the current calculation is the correct one, as it takes the missing data of each population separately into account. The simple solution is to set all negative values to 0.

As for your aside about the result being the same independent of the window averaging question: Yes, that is expected for "good" data. However, it starts making a difference once you apply per-sample filters, as in these cases, the number of "valid" positions can differ between populations, and that will be taken into account for the window averaging per sample. In your case though, where no additional filters were applied, the denominator is simply 100 (your window size) in all cases, and you are right that it then simply cancels out.

Let me know if that answers your questions, and is clear. Also, is that the way then that you expect these values to be computed?

Cheers and so long
Lucas

**Comment by VitoriaHorvathMiranda** [comment]
Hey Lucas!

Thank you so much for your fast and thoughtful response!

I could perfectly understand the issue now: I thought that missing data would automatically be masked out. The logic behind this is that, at least in my case, positions with depth equal to zero were already filtered and probability didn’t pass one of my filters. In cases where a position is missing in one population, I believe that means we lack information for that region, and therefore, it shouldn’t be included in the calculation of any statistics, even though we have the information for the other population.

The way the program is computing now in practice assumes that those regions are fixed (which we do not have evidence for) to compute the average pi-within while accepting that pi-between can’t be calculated for that region. As a result, I imagine pi-within could be inflated relative to pi-between in regions with missing data, which explains the negative FST values I’ve been seeing.

If there is missing data for pop 1 this is what it does to compute the average pi-within:
0.5*(0 +pi-pop2) = pi-pop2*0.5

This is what I think it should be doing:
0.5*(NA + pi-pop2) = NA

I’m not sure, but I think setting ‘--filter-sample-min-read-depth 1‘ would fix that?

Thanks again for your help!
Best regards,
Vitória

**Comment by lczech** [comment]
Yes, your reasoning is on point there! And I was actually about to add a comment that as an alternative to filtering out negative values after the fact, you could also just play around with the numerical filters as needed. That should indeed also remove this issue, as you just pointed out.

As for the question if zero-count positions should or should not be filtered out automatically: That was basically the major change from v0.3.0 to later, where now they are not filtered out by default (see also [here](https://github.com/lczech/grenedalf/wiki/Filtering#snp-detection)). My reasoning for this was that it's easy enough to set a numerical filter to remove positions based on the exact use case. But filtering out such positions by default might not be what's needed in every use case, so they are kept unless a filter is applied.

Hope that helps :-)
Lucas

**Comment by lczech** [comment]
Okay, I've also added some more explanation about this to the end of [this paragraph](https://github.com/lczech/grenedalf/wiki/Filtering#numerical-filters). Let me know if that makes sense :-)

**Comment by lczech** [comment]
Hey Vitória,

thanks for the feedback and for bringing this to my attention. I've added a short warning about this to the [fst command doc](https://github.com/lczech/grenedalf/wiki/Subcommand:-fst) now to make users aware of this, linking to this issue here.

I guess we can close the issue then? Feel free to re-open or start a new one if you have any more questions or trouble with grenedalf!

Cheers
Lucas
