### ISSUE TITLE
Suggestion: Include MASK files for correct calculation of  per-site averages

### ISSUE THREAD

**Issue by capoony** [lczech/grenedalf#5]
Hi Lucas, 

me again! I have another suggestion that may be useful as you are restructuring your code right now. One common problem with PoPoolation is, that it does not take into account that not only SNPs but also non-polymorphic positions may not pass heuristic SNP-calling paramters or a posteriori filtering. This commonly leads to an underestimation of per-site averages for any popgen statistics when simply dividing the sum of absolute values by the window-size. To yield correct values, the window-sizes need to be adjusted to account for all sites that do not pass the same criteria (heuristic parameters, removal of low-complexity regions, etc.) as the actual SNPs. We describe this issue in the Methods section of our paper (https://academic.oup.com/mbe/article/37/9/2661/5837682)

One way to pass such information is to either read BED or MASK files. The latter are FASTA-type files, where all positions with a `0` are retained and all positions >0 are ignored. See also the documentation of [vcftools](https://vcftools.github.io/man_latest.html)
```
>1
0000011111222...
>2
2222211111000...
```

Based on this information, the window-size could be adjusted to calculate correct per-site averages. Hope this is helpful and apologies for swamping you with stuff ;-)

Cheers, Martin

**Comment by lczech** [comment]
Follow up question for @capoony and @jeffspence: 

The mask file is easy enough to use for counting positions to be used for computing relative Theta, as the mask file format of vcftools gives information per position. Similarly, I can imagine to use BIM/MAP files of PLINK, where the provided positions are interpreted as "used", and non-provided positions as "masked".

However, formats such as BED, or for that matter GFF/GTF, describe regions, instead of individual positions. How would you suggest then to use those formats to compute relative Theta? I could imagine to use the "score" column of BED, and interpret that as number of non-masked positions per region? Or what did you have in mind?

**Comment by jeffspence** [comment]
I was thinking something like the `--mask` option in smc++ (https://github.com/popgenmethods/smcpp), where the regions specified in the .bed file are all of the positions that should be treated as missing. That is, the number of non-masked positions per region would be the number of positions in the region that are not covered by some interval in the .bed file.

**Comment by lczech** [comment]
Hi @capoony,

finally the (hopefully) proper ways of normalizing windows is now implemented in [grenedalf v0.5.0](https://github.com/lczech/grenedalf/releases/tag/v0.5.0), as you also saw from the email earlier today with @alanbergland. Just wanted to bring this up here, and finally close this issue. If you have any questions, comments, or issues with the new implementation, please let me know! 

All the best
Lucas
