### ISSUE TITLE
Unordered chromosomes error

### ISSUE THREAD

**Issue by jkreinz** [lczech/grenedalf#6]
Hi there,

Excited to use grenedalf, thanks for your work on this! I'm providing multiple VCFs to a grenedalf frequency call to start, and am getting the following error
`what():  Malformed VCF file /DATA/home/juliak//pathogen_evo/vcfs/poolseq/Sample_100.Q20.ANNO.vcf: unordered chromosomes and positions going from NODE_9_length_182528_cov_101.096338:62956 to NODE_10_length_150116_cov_77.788002:93243
Aborted (core dumped)`

I've taken a look at the vcfs in this region and they look correctly sorted (see below). Is there something about how the chromosome name is parsed that might be throwing this error? 

Thanks,
Julia

![Screenshot 2023-05-30 at 2 38 44 PM](https://github.com/lczech/grenedalf/assets/15037621/8703561d-5abc-4644-b57b-6bcfa62351ab)

**Comment by lczech** [comment]
Hi @jkreinz,

the requirement of grenedalf to have chromosomes sorted is an unfortunate simplification in the code that I made to keep the implementation simple... I'm hoping to implement a more general algorithm at some point that will be able to deal with other orders as well. But for now, chromosomes have to be sorted.

The sorting is currently implemented with [lexicographical sorting](https://stackoverflow.com/a/68339903/4184258). In your particular case, the sorting order of `NODE_9` and `NODE_10` is decided based on left-to-right character comparisons, meaning the `NODE_` part is identical in both, and then the first characters where both differ are `9` and `1`, which are hence in the "wrong" order (with respect to lexicographical sorting order). So, with respect to that order, your chromosomes are in fact out of order.

Before I find the time to implement the better algorithm, a quick fix for you is to rename your chromosomes to `NODE_09`, so that there is a leading `0` that will be compared to the `1` of `NODE_10`, and hence give the correct order. Generally, when working with numbers and strings (words) mixed, it is a good idea to have fixed-sized numbers with leading zeros, for that reason.

Let's also keep this issue open for now, because an alternative quick solution from my side would be to sort instead with respect to natural numbers as well. That would still be a well-defined sorting order, but would allow your use case. I'll have to see if that can be done.

Sorry for the inconvenience - it is a shortcoming that I had in mind before, but did not have the time to fix yet.

Cheers and so long
Lucas

**Comment by lczech** [comment]
Hey @jkreinz,

I've just implemented a simple solution that makes things easier: You can now provide a reference genome, or a `dict` or `fai` file thereof, containing your chromosomes/contigs in the order of your vcf input file. If provided, instead of expecting lexicographical order, the order of that reference will be used then instead. That should make it straightforward to get this to work for you.

So, please get the latest `dev` branch, and compile again.

Hope that helps - if you have any more trouble, feel free to re-open the issue or start a new one!

Cheers
Lucas
